// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT2JqJeNZGOJTJVGPl6gT9XeKrvuWXLF8',
    appId: '1:658589950586:web:b8254015b0facc748391c3',
    messagingSenderId: '658589950586',
    projectId: 'test-9188a',
    authDomain: 'test-9188a.firebaseapp.com',
    storageBucket: 'test-9188a.appspot.com',
    measurementId: 'G-DEERFKRBB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXCapUSbFnCc-7ERT-d7DzDGkrQx6_ydg',
    appId: '1:658589950586:android:b5c21a19c452486a8391c3',
    messagingSenderId: '658589950586',
    projectId: 'test-9188a',
    storageBucket: 'test-9188a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTOttmGNPrBnSdFTJ-itctGIPfUipOScs',
    appId: '1:658589950586:ios:55f76bd17213ff5f8391c3',
    messagingSenderId: '658589950586',
    projectId: 'test-9188a',
    storageBucket: 'test-9188a.appspot.com',
    iosClientId: '658589950586-opjn8vgchnbmbp8thvgbl262ebf7n4jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.app3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTOttmGNPrBnSdFTJ-itctGIPfUipOScs',
    appId: '1:658589950586:ios:55f76bd17213ff5f8391c3',
    messagingSenderId: '658589950586',
    projectId: 'test-9188a',
    storageBucket: 'test-9188a.appspot.com',
    iosClientId: '658589950586-opjn8vgchnbmbp8thvgbl262ebf7n4jr.apps.googleusercontent.com',
    iosBundleId: 'com.example.app3',
  );
}
